# inspiration from https://github.com/symplify/symplify/blob/main/.github/workflows/unit_tests.yaml

name: Unit Tests

on:
  pull_request: ~

env:
  # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
  COMPOSER_ROOT_VERSION: "dev-main"

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    name: PHP 8.0 tests

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - uses: "ramsey/composer-install@v1"

      - run: make environment

      - run: make test-all